<template>
    <div id="app" class="app" >
        <div class="map">
            <l-map
                    style="height: 100%; width: 100%"
                    :zoom="zoom"
                    :bounds="bounds"
                    :maxBounds="bounds"
                    :minZoom="11"
                    :maxZoom="18"
                    @click.right="rightClick($event)"
            >
                <l-tile-layer :url="url"
                              :attribution="attribution"/>
                <l-geo-json
                        :v-if="avoidPolygons !== null"
                        :geojson="avoidPolygons"
                        :options="onEachFeatureFunction()"
                        :options-style="styleFunction('avoid')"
                />
                <l-geo-json
                        v-if="stuttgart.show"
                        :geojson="stuttgart.value"
                        :options="onEachFeatureFunction()"
                        :options-style="styleFunction('stuttgart')"
                />
                <l-geo-json
                        v-if="districts.show"
                        :geojson="districts_geojson"
                        :options="onEachFeatureFunction()"
                        :options-style="styleFunction"
                />
                <l-geo-json
                        v-if="route !== null"
                        :geojson="routeLine"
                        :options="onEachFeatureFunction()"
                        :options-style="styleFunction('line')"
                />
                <l-marker v-for="(m,i) in markersList"
                          :draggable="true"
                          :lat-lng.sync="m.position"
                          @dragend="dragEnd()"
                          :key="'marker-'+i"
                >
                </l-marker>
                <l-geo-json
                        :geojson="stations.value"
                        :options-style="styleFunction"
                ></l-geo-json>
            </l-map>
        </div>
        <div id="sidebar" class="sidebar" style="">
            <h3>Healthy routing in Stuttgart city</h3>
            <p>Find a healthy <b>bicycle</b>-route through Stuttgart city using openrouteservice by avoiding areas above a specific value
                of the <a target='_blank' href="https://airindex.eea.europa.eu/#">EAQI</a>.
            </p>
            <p>Start and end points can be placed by <b>right-clicking</b> on the map</p>
            <p>The category areas were generated by interpolating over the aggregated average PM 2.5 values
                of multiple months (early 2020) for every hour of the day</p>
            <h4 class="settings">Settings</h4>
            <div class="label"> Lowest Air Quality Index level to avoid:</div>
            <v-slider
                    id="pm-slider"
                    class="slider"
                    v-model="eaqi"
                    :data="categories"
                    :ticks="'always'"
                    :tooltip="'none'"
                    :duration="0.3"
                    :marks="true"
                    :adsorb="true"
                    :tick-size="2"
                    :width="'80%'"
                    :height="'5px'"
                    :useKeyboard="true"
                    @change="changeCategory"
            ></v-slider>
            <div class="label"> Time of the day:
            </div>
            <v-slider
                    class="slider"
                    v-model="hour"
                    :data="Array.from({length:24},(v,k)=>k)"
                    :ticks="'always'"
                    :tooltip="'focus'"
                    :duration="0.3"
                    :marks="hourSliderLabel()"
                    :adsorb="true"
                    :tick-size="2"
                    :width="'80%'"
                    :height="'5px'"
                    :useKeyboard="true"
                    @change="changeHour"
            ></v-slider>
            <label>
                Show stations
                <input type="checkbox" v-model="stations.show" @change="fetchStations">
            </label>
            <label>
                Highlight stuttgart administrative area
                <input type="checkbox" v-model="stuttgart.show">
            </label>
<!--            <label>-->
<!--                Show stuttgart districts-->
<!--                <input type="checkbox" v-model="districts.show">-->
<!--            </label>-->
            <div class="routeOutlet" :style="{color: requestStats.dist ? 'green' : 'red'}">
                Route request information
                <div v-if="requestStats.msg">{{requestStats.msg}}</div>
                <div v-if="requestStats.dist">Route distance (m): {{requestStats.dist}}</div>
                <div v-if="requestStats.dur">Route duration (sec): {{requestStats.dur}}</div>
            </div>
        </div>
    </div>
</template>
<script src="./app.js">

</script>
<style>
    @import '~vue-slider-component/theme/default.css';
    @import 'app.css';
</style>
